openapi: 3.0.3
info:
  title: GitHub Actions Monitor API Contract
  description: API contract for GitHub Actions monitoring functionality
  version: 1.0.0

paths:
  /repos/{owner}/{repo}/actions/runs:
    get:
      summary: List workflow runs for a repository
      description: Fetches recent workflow runs for a specific repository
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
          description: Repository owner (user or organization)
        - name: repo
          in: path
          required: true
          schema:
            type: string
          description: Repository name
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
            default: 50
            maximum: 100
          description: Number of results per page
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [queued, in_progress, completed]
          description: Filter by workflow run status
        - name: branch
          in: query
          required: false
          schema:
            type: string
          description: Filter by branch name
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowRunsResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'

  /repos/{owner}/{repo}/actions/runs/{run_id}:
    get:
      summary: Get a specific workflow run
      description: Fetches details of a specific workflow run
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
        - name: run_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowRun'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /repos/{owner}/{repo}/actions/runs/{run_id}/logs:
    get:
      summary: Download workflow run logs
      description: Downloads logs for a specific workflow run as a zip file
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
        - name: run_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response - logs as zip file
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '302':
          description: Redirect to log download URL
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /repos/{owner}/{repo}:
    get:
      summary: Get repository information
      description: Fetches basic repository information
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Repository'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /rate_limit:
    get:
      summary: Get rate limit status
      description: Fetches current API rate limit status
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateLimit'

components:
  schemas:
    WorkflowRunsResponse:
      type: object
      properties:
        total_count:
          type: integer
          description: Total number of workflow runs
        workflow_runs:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowRun'

    WorkflowRun:
      type: object
      required:
        - id
        - name
        - head_branch
        - head_sha
        - status
        - created_at
        - updated_at
        - html_url
      properties:
        id:
          type: integer
          description: Unique identifier for the workflow run
        name:
          type: string
          description: Name of the workflow
        head_branch:
          type: string
          description: Branch the workflow run was triggered on
        head_sha:
          type: string
          description: Commit SHA that triggered the workflow run
        status:
          $ref: '#/components/schemas/WorkflowStatus'
        conclusion:
          $ref: '#/components/schemas/WorkflowConclusion'
        created_at:
          type: string
          format: date-time
          description: When the workflow run was created
        updated_at:
          type: string
          format: date-time
          description: When the workflow run was last updated
        actor:
          $ref: '#/components/schemas/Actor'
        html_url:
          type: string
          format: uri
          description: URL to the workflow run in GitHub
        logs_url:
          type: string
          format: uri
          description: URL to download the workflow run logs

    WorkflowStatus:
      type: string
      enum:
        - queued
        - in_progress
        - completed

    WorkflowConclusion:
      type: string
      enum:
        - success
        - failure
        - cancelled
        - skipped
        - timed_out

    Actor:
      type: object
      properties:
        login:
          type: string
          description: Username of the actor
        type:
          type: string
          enum: [User, Bot]
          description: Type of actor

    Repository:
      type: object
      required:
        - name
        - full_name
        - default_branch
      properties:
        name:
          type: string
          description: Repository name
        full_name:
          type: string
          description: Full repository name in "owner/repo" format
        default_branch:
          type: string
          description: Default branch name
        private:
          type: boolean
          description: Whether the repository is private
        html_url:
          type: string
          format: uri
          description: URL to the repository in GitHub

    RateLimit:
      type: object
      properties:
        resources:
          type: object
          properties:
            core:
              $ref: '#/components/schemas/RateLimitResource'
            search:
              $ref: '#/components/schemas/RateLimitResource'
            graphql:
              $ref: '#/components/schemas/RateLimitResource'

    RateLimitResource:
      type: object
      properties:
        limit:
          type: integer
          description: Maximum number of requests allowed
        remaining:
          type: integer
          description: Number of requests remaining
        reset:
          type: integer
          description: Unix timestamp when rate limit resets

  responses:
    Unauthorized:
      description: Authentication failed
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              documentation_url:
                type: string

    Forbidden:
      description: Access forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              documentation_url:
                type: string

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              documentation_url:
                type: string

    UnprocessableEntity:
      description: Validation failed
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                items:
                  type: object
                  properties:
                    resource:
                      type: string
                    field:
                      type: string
                    code:
                      type: string

security:
  - BearerAuth: []

securitySchemes:
  BearerAuth:
    type: http
    scheme: bearer
    bearerFormat: GitHub Personal Access Token